# Generated by Django 2.2.2 on 2019-06-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='join_trip',
            field=models.ManyToManyField(related_name='joining', to='myapp.User'),
        ),
    ]
